### ISSUE TITLE
Go update requires build changes

### ISSUE THREAD

**Issue by stmcginnis** [bottlerocket-os/bottlerocket-sdk#144]
**Issue or Feature Request:**

The kubernetes project now builds with Go 1.21.4. In attempting to update the SDK to use a matching version, it looks like there has been some changes to the Go build process that now result in errors during the build:

```
 => ERROR [sdk-go 8/9] RUN   export GOARCH="${!GOARCH_ARCH}" ;   export CC="${TARGET}-gcc" ;   export CC_FOR_TARGET="${TARGET}-gcc" ;   export CC_FO  23.8s
------
 > [sdk-go 8/9] RUN   export GOARCH="${!GOARCH_ARCH}" ;   export CC="${TARGET}-gcc" ;   export CC_FOR_TARGET="${TARGET}-gcc" ;   export CC_FOR_${GOOS}_${GOARCH}="${TARGET}-gcc" ;   export CXX="${TARGET}-g++" ;   export CXX_FOR_TARGET="${TARGET}-g++" ;   export CXX_FOR_${GOOS}_${GOARCH}="${TARGET}-g++" ;   export GOFLAGS="-mod=vendor" ;   go install std cmd &&   go install -buildmode=pie std cmd:
4.527 # cmd/cgo/internal/test/issue8828
4.527 cgo-gcc-prolog: In function '_cgo_cd757160f43e_Cfunc_foo':
4.527 cgo-gcc-prolog:47:33: warning: unused variable '_cgo_a' [-Wunused-variable]
12.86 # cmd/cgo/internal/test
12.86 In file included from _cgo_export.c:4:
12.86 cgo_thread_lock.go:14:13: error: 'Ctid' defined but not used [-Werror=unused-function]
12.86 cc1: note: unrecognized command-line option '-Wno-unknown-warning-option' may have been intended to silence earlier diagnostics
12.86 cc1: all warnings being treated as errors
------
Dockerfile:489
--------------------
 488 |       GO111MODULE="auto"
 489 | >>> RUN \
 490 | >>>   export GOARCH="${!GOARCH_ARCH}" ; \
 491 | >>>   export CC="${TARGET}-gcc" ; \
 492 | >>>   export CC_FOR_TARGET="${TARGET}-gcc" ; \
 493 | >>>   export CC_FOR_${GOOS}_${GOARCH}="${TARGET}-gcc" ; \
 494 | >>>   export CXX="${TARGET}-g++" ; \
 495 | >>>   export CXX_FOR_TARGET="${TARGET}-g++" ; \
 496 | >>>   export CXX_FOR_${GOOS}_${GOARCH}="${TARGET}-g++" ; \
 497 | >>>   export GOFLAGS="-mod=vendor" ; \
 498 | >>>   go install std cmd && \
 499 | >>>   go install -buildmode=pie std cmd
 500 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c export GOARCH=\"${!GOARCH_ARCH}\" ;   export CC=\"${TARGET}-gcc\" ;   export CC_FOR_TARGET=\"${TARGET}-gcc\" ;   export CC_FOR_${GOOS}_${GOARCH}=\"${TARGET}-gcc\" ;   export CXX=\"${TARGET}-g++\" ;   export CXX_FOR_TARGET=\"${TARGET}-g++\" ;   export CXX_FOR_${GOOS}_${GOARCH}=\"${TARGET}-g++\" ;   export GOFLAGS=\"-mod=vendor\" ;   go install std cmd &&   go install -buildmode=pie std cmd" did not complete successfully: exit code: 1
make: *** [Makefile:16: sdk] Error 1
```

It's possible we just need some different build flags, but requires further investigation.

**Comment by markusboehme** [comment]
@jpculp I think this is done, right? Unless changing the warning flags to the compiler was a stop-gap measure?

**Comment by jpculp** [comment]
Correct. These changes were included in v0.36.0 and now v0.37.0.
